# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170406_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='improvement',
            field=models.CharField(default='Oleks tore kui saaks rohkem pannkooke', max_length=1000),
        ),
    ]
