# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_petition_improvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='picture',
            field=models.ImageField(default='hello/static/images/anatoomikum.jpg', upload_to=''),
        ),
    ]
